package com.onderogluserdar.ticketing.common.error;

public enum ErrorCode {
    EVENT_ALREADY_PUBLISHED,
    CAPACITY_BELOW_RESERVED,
    INVALID_RESERVATION_STATE,
    EMAIL_ALREADY_REGISTERED,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    EVENT_NOT_FOUND,
    EVENT_ACCESS_DENIED,
    EVENT_NOT_PUBLISHED,
    INSUFFICIENT_CAPACITY,
    RESERVATION_NOT_FOUND,
    RESERVATION_ACCESS_DENIED,
    VALIDATION_ERROR,
    IDEMPOTENCY_KEY_CONFLICT,
    INVALID_REQUEST,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
