spring:
  application:
    name: secure-ticketing-api

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketing}
    username: ${DB_USERNAME:ticketing}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080
